### ISSUE TITLE
Use exported ReSpec HTML for published/final versions

### ISSUE THREAD

**Issue by coolharsh55** [SEMICeu/MLDCAT-AP#23]
The latest release HTML at https://semiceu.github.io/MLDCAT-AP/releases/2.1.0/ show the respec error on top right corner, as well as loads many (devel/debug) css/js scripts which delays loading the page. These are helpful when the document is in draft form, but when the document is finalised the export feature should be used which removes all these and streamlines the HTML document to a 'publication ready' state. 

See https://respec.org/docs/#static-snapshots for instructions. Do this manually by clicking on the `ReSpec` button on top right corner and export or use the CLI tool to export this.

**Comment by EmidioStani** [comment]
Hello @coolharsh55 ,

thanks for reporting this ! in the internal draft of the current version the respec error has been solved:

https://semiceu.github.io/uri.semic.eu-generated/MLDCAT-AP/releases/2.1.0/

is it fine ? or do you see something else ? especially in reference to "loads many (devel/debug) css/js scripts" ?

**Comment by coolharsh55** [comment]
Hi. I still see the ReSpec developer's version (easy tell: top right corner has a clickable ReSpec logo) -- see https://w3c.github.io/dpv/2.1/dpv/ for example which is the exported document and doesn't contain it. The developer's version loads many additional scripts and functions as part of things like spellcheck, reference management, etc. which is what I'm referring to, and which slows down the page. Its not needed when the document is final/published. No harm in keeping it, but better to use the publish option. I can submit a PR if needed if you want to see the diff with a script to export (its just repeating what's at https://respec.org/docs/#static-snapshots) -- let me know.

**Comment by coolharsh55** [comment]
@EmidioStani so this is not something to configure in the respec json in HTML, but rather an external process as part of publishing. The workflow we use for DPV is something like this:

1. create new HTML doc, use respec json config to declare title, etc. -- we have this in folders version suffixed with `-dev` e.g. `2.2-dev`
2. discuss and refine the doc in `2.2-dev` - the respec libraries help identify missing references and other errors (that's the number shown on top right as errors and warnings)
3. once we decide to publish, we create `2.2` as the version folder, and I use the `respec --src draft.html --out final.html` command to create the static snapshop (assuming respec is locally installed using `npm install --global respec`)
4. if there is any change in the HTML, e.g. typo, we export it again (whether version changes or not depends on the change)

For MLDCAT-AP, this means the following:

1. for current releases `1.0.0`, `2.0.0`, `2.1.0` use the above export option to get the final/published version from respec
2. for draft releases (assuming you have a `2.2.0` being worked on somewhere), continue using respec as you currently are
3. for future releases, when it is to be published, use the export option as above for publishing it as a final release

**Comment by EmidioStani** [comment]
Thanks it is clear, I believe we (SEMIC editors) need to discuss on the process and take a decision, thanks for the input !

**Comment by coolharsh55** [comment]
@EmidioStani let me know if I can assist with it. I'm going through MLDCAT-AP closely as we have the [AI](https://w3id.org/dpv/ai) and [AI-Act](https://w3id.org/dpv/legal/eu/aiact) extensions for the DPV which we're expanding significantly in the DPV 2.2 and 2.3 updates this year, and I don't want duplication and incompatibility if possible. My focus is around how MLDCAT-AP meets requirements of GDPR and AI Act (amongst others) and more importantly to what extent is it useful to meet obligations of documentation and auditing compliance.
